
export interface Resume {
  name: string;
  email: string;
  year: string;
  major: string[];
  college: string[];
  visa: string;
  link: string;
}

export const resumes: Resume[] = [
  {
    name: 'Afsha Rehman ',
    email: 'rehma068@umn.edu',
    year: 'Senior',
    major: ["Chemical Engineering"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1KR5JfWzCR231zFowvYEFYIkeoP3nY-gq/preview',
  },
  {
    name: 'Annalise Xiao',
    email: 'xiao0332@umn.edu',
    year: 'Junior',
    major: ["Data science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1mFSg6BS5OlirMBfsMEM5mVAjEKFMK5mQ/preview',
  },
  {
    name: 'Ansh Patel',
    email: 'pate1011@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1Aevql40Alvtvp7yemy34eKAuCTe7HTKu/preview',
  },
  {
    name: 'Eunice Tong',
    email: 'tong0163@umn.edu',
    year: 'Junior',
    major: ["Chemistry"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1qeGKwzLj_wPPmpsy8edvxrcFFjGuTWDQ/preview',
  },
  {
    name: 'Harini Kuchibhotla',
    email: 'kuchi027@umn.edu',
    year: 'Sophomore',
    major: ["Computer Science","Data Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1VY3kJhf7BlcRSiUDAqDazWXvdxuNWs1G/preview',
  },
  {
    name: 'Henry Le',
    email: 'le000379@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1uy5picyOXA-fijUGs5sJrWhzeVNlzL-J/preview',
  },
  {
    name: 'Hillary Vo',
    email: 'vo000074@umn.edu',
    year: 'Senior',
    major: ["Mathematics"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1NTfMfzv8cYPLyF5bWJNtuflGEUaBsBIm/preview',
  },
  {
    name: 'Jiaxi Tang',
    email: 'tang0773@umn.edu',
    year: 'Junior',
    major: ["Computer Science","Graphic Design"],
    college: ["College of Science and Engineering","College of Design"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1eu9TO3jFwE40A4VXvJawN_BQJV1JhRtz/preview',
  },
  {
    name: 'Joseph Hoang',
    email: 'hoang340@umn.edu',
    year: 'Senior',
    major: ["Aerospace Engineering","Mathematics"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1jPH2J0vHQDEVALfVLzhdSAJxBGF9BoX7/preview',
  },
  {
    name: 'Julie Bondy',
    email: 'bondy031@umn.edu',
    year: 'Graduate',
    major: ["Microbial Engineering"],
    college: ["College of Biological Sciences"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1Nlfs9DmH6xGoWSx-thRJEMTlqNUDy1e8/preview',
  },
  {
    name: 'Lahari Hosur',
    email: 'hosur004@umn.edu',
    year: 'Sophomore',
    major: ["Aerospace Engineering"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1vW1LNYpcUOm3Oiwa_OXhURNV4njSJEiX/preview',
  },
  {
    name: 'Nilay Singh Mer',
    email: 'mer00002@umn.edu',
    year: 'Sophomore',
    major: ["Management Information Systems","Finance"],
    college: ["Carlson School of Management"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1bkGKi3goX8viwVh_EQ9_fJtVNtWn2aOn/preview',
  },
  {
    name: 'Pearl Jain',
    email: 'jain0377@umn.edu',
    year: 'Sophomore',
    major: ["Computer Science","Data Science"],
    college: ["College of Science and Engineering"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1FgY5mTnVH9dFtfa72_VIAToiQpeo1GFD/preview',
  },
  {
    name: 'Riya Bharti',
    email: 'bhart022@umn.edu',
    year: 'Junior',
    major: ["Computer Science","Mathematics"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1MI6TyIkXsaT6mjKAK248MjZjs9LlLcxB/preview',
  },
  {
    name: 'Shreya Srivastava ',
    email: 'sriva263@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1J-GDBT4ssnqjSiweDd1Gk-4kbFnaydAl/preview',
  },
  {
    name: 'Tommy Le',
    email: 'le000397@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1jJFBem9LKq9FelWN0Tk5pqdtz8Qx6shF/preview',
  },
];