
export interface Resume {
  name: string;
  email: string;
  year: string;
  major: string[];
  college: string[];
  visa: string;
  link: string;
}

export const resumes: Resume[] = [
  {
    name: 'Jiaxi Tang',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Junior',
    major: ["Computer Science", "Graphic Design"],
    college: ["College of Science and Engineering", "College of Design"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  },
  {
    name: 'Corporate 1',
    email: 'tang0773@umn.edu',
    year: 'Senior',
    major: ["Chemical Engineering"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Jiaxi 1',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Junior',
    major: ["Data science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  },
  {
    name: 'Corporate 2',
    email: 'tang0773@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Jiaxi 2',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Junior',
    major: ["Chemistry"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  },
  {
    name: 'Corporate 3',
    email: 'tang0773@umn.edu',
    year: 'Sophomore',
    major: ["Data science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Jiaxi 3',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  },
  {
    name: 'Corporate 4',
    email: 'tang0773@umn.edu',
    year: 'Senior',
    major: ["Mathematics"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Jiaxi 4',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Junior',
    major: ["Finance"],
    college: ["Carlson School of Management"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  },
  {
    name: 'Corporate 5',
    email: 'tang0773@umn.edu',
    year: 'Senior',
    major: ["Aerospace Engineering"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Jiaxi 5',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Graduate',
    major: ["Microbial Engineering"],
    college: ["College of Biological Sciences"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  },
  {
    name: 'Corporate 6',
    email: 'tang0773@umn.edu',
    year: 'Sophomore',
    major: ["Aerospace Engineering"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Jiaxi 6',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Sophomore',
    major: ["Management Information Systems"],
    college: ["Carlson School of Management"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  },
  {
    name: 'Corporate 7',
    email: 'tang0773@umn.edu',
    year: 'Sophomore',
    major: ["Data science"],
    college: ["College of Science and Engineering"],
    visa: 'Yes',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Jiaxi 7',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Junior',
    major: ["Mathematics"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  },
  {
    name: 'Corporate 8',
    email: 'tang0773@umn.edu',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1UErZnr5yfm9vZ4-4fTzc3Q44HLdBKDwh/preview',
  },
  {
    name: 'Jiaxi 8',
    email: 'jt.jiaxitang@gmail.com',
    year: 'Junior',
    major: ["Computer Science"],
    college: ["College of Science and Engineering"],
    visa: 'No',
    link: 'https://drive.google.com/file/d/1W9fT9UDUHvgqgpwLxB0XqbsaVbywmTkH/preview',
  }
];
